title = "Fernglasz"

[menu]
  [[menu.main]]
    identifier = "login"
    name = "Login"
    url = "http://localhost:3000/signin"
    weight = 10

  [[menu.main]]
    identifier = "signup"
    name = "Sign Up"
    url = "http://localhost:3000/signup"
    weight = 20
