title = "Fernglasz"

[menu]
  [[menu.main]]
    identifier = "login"
    name = "Login"
    url = "https://www.fernglasz.com/signin"
    weight = 10

  [[menu.main]]
    identifier = "signup"
    name = "Sign Up"
    url = "https://www.fernglasz.com/signup"
    weight = 20
