title = "Fernglasz"

[menu]
  [[menu.main]]
    identifier = "login"
    name = "Login"
    url = "/signin"
    weight = 10

  [[menu.main]]
    identifier = "signup"
    name = "Sign Up"
    url = "/signup"
    weight = 20
