[build]
  command = "hugo"
  publish = "public"

  [[headers]]
for = "/*"
  [headers.values]
  Content-Security-Policy = "frame-ancestors 'self' http://localhost:3000 https://fernglasz.web.app"

[[headers]]
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"